
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- This configuration is split into multiple files, required below.
-- See https://wiki.hypr.land/Configuring/Start/

require("monitors")
require("autostart")
require("env")
require("permissions")
require("look_and_feel")
require("layouts")
require("misc")
require("input")
require("keybindings")
require("window_rules")
