#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    background = 'transparent'
    foreground = '#676f71'
    template = '{{ if .SSHSession }} {{ .UserName }}@{{ .HostName }} {{ end }}'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = '#698b85'
    template = ' {{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#b4bbaa'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}<#a5ac97>*</>{{ end }} <#77a29b>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#a9b495'
    background = 'transparent'
    template = '{{ if ne .Code 0 }} {{ .Code }} {{ end }}'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#a5ac97'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    template = '{{ if .Root }}<#ff5555>#</>{{ else }}<#698b85>$</>{{ end }} {{ if eq .Code 0 }}<#b2cfb8>❯</>{{ else }}<#a9b495>❯</>{{ end }}'

[transient_prompt]
  background = 'transparent'
  template = '{{ if .Root }}<#ff5555>#</>{{ else }}<#698b85>$</>{{ end }} {{ if eq .Code 0 }}<#b2cfb8>❯</>{{ else }}<#a9b495>❯</>{{ end }} '
  right_template = '{{ if ne .Code 0 }}<#a9b495>{{ .Code }}</>{{ end }}'

[secondary_prompt]
  background = 'transparent'
  template = '{{ if .Root }}<#ff5555>#</>{{ else }}<#698b85>$</>{{ end }} <#676f71>❯❯</> '
